exports.extensionMappings = {
	//images
	".jpg": "images",
	".jpeg": "images",
	".png": "images",
	".gif": "images",
	".svg": "images",
	".webp": "images",
	".bmp": "images",
	".ico": "images",
	".tiff": "images",
	".tif": "images",

	//videos
	".mp4": "videos",
	".mkv": "videos",
	".flv": "videos",
	".avi": "videos",
	".mov": "videos",
	".wmv": "videos",
	".webm": "videos",
	".mpg": "videos",
	".mpeg": "videos",
	".m4v": "videos",
	".3gp": "videos",

	//audio
	".mp3": "audio",
	".m4a": "audio",
	".wav": "audio",
	".aac": "audio",
	".ogg": "audio",
	".flac": "audio",
	".wma": "audio",
	".alac": "audio",

	//documents
	".doc": "documents",
	".docx": "documents",
	".txt": "documents",
	".rtf": "documents",
	".md": "documents",
	".odt": "documents",

	//presentations
	".ppt": "documents",
	".pptx": "documents",
	".key": "documents",

	//pdf
	".pdf": "documents",

	//code
	".py": "code",
	".js": "code",
	".ts": "code",
	".json": "code",
	".jsx": "code",
	".java": "code",
	".c": "code",
	".html": "code",
	".htm": "code",
	".css": "code",
	".scss": "code",
	".sass": "code",
	".less": "code",
	".php": "code",
	".go": "code",
	".rb": "code",
	".sql": "code",
	".swift": "code",
	".kt": "code",
	".dart": "code",
	".h": "code",
	".cpp": "code",
	".cs": "code",
	".pl": "code",
	".vb": "code",
	".lua": "code",
	".sh": "code",
	".r": "code",
	".m": "code",
	".ejs": "code",
	".jsp": "code",
	".asp": "code",
	".aspx": "code",
	".tsx": "code",
	".vue": "code",
	".yml": "code",
	".yaml": "code",
	".xml": "code",
	".ini": "code",
	".toml": "code",
	".lock": "code",
	".gitignore": "code",
	".env": "code",
	".env.local": "code",
	".env.development": "code",
	".env.test": "code",
	".env.production": "code",
	".babelrc": "code",
	".prettierrc": "code",
	".prettierignore": "code",
	".eslintrc": "code",
	".eslintignore": "code",
	".stylelintrc": "code",
	".stylelintignore": "code",
	".dockerignore": "code",
	".dockerfile": "code",
	".editorconfig": "code",
	".gitattributes": "code",
	".gitmodules": "code",
	".gitkeep": "code",
	".gitpod.yml": "code",
	".gitpod.dockerfile": "code",
	".gitpod.Dockerfile": "code",
	".gitpod.yml": "code",
	".gitpod.dockerfile": "code",
	".gitpod.Dockerfile": "code",
	".gitpod.yml": "code",
	".gitpod.dockerfile": "code",
	".gitpod.Dockerfile": "code",
	".gitpod.yml": "code",

	//designs
	".ai": "designs",
	".psd": "designs",
	".sketch": "designs",
	".fig": "designs",
	".eps": "designs",
	".indd": "designs",
	".xd": "designs",

	//archives
	".zip": "archives",
	".rar": "archives",
	".tar": "archives",
	".7z": "archives",
	".gz": "archives",
	".bz2": "archives",
	".xz": "archives",
	".iso": "archives",
	".dmg": "archives",
	".pkg": "archives",
	".deb": "archives",
	".rpm": "archives",

	//executables
	".exe": "executables",
	".msi": "executables",
	".apk": "executables",
	".app": "executables",
	".jar": "executables",

	//spreadsheets
	".xls": "spreadsheets",
	".xlsx": "spreadsheets",
	".ods": "spreadsheets",
	".csv": "spreadsheets",
	".tsv": "spreadsheets",
	".ods": "spreadsheets",
	".gsheet": "spreadsheets",
	".numbers": "spreadsheets",
	".xlsm": "spreadsheets",
	".xlsb": "spreadsheets",
	".xltx": "spreadsheets",
	".xltm": "spreadsheets",
	".xlam": "spreadsheets",
	".xll": "spreadsheets",
	".xlw": "spreadsheets",
	".xlr": "spreadsheets",

	// ... add more extensionMappings as needed
};
